# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


stockCPP <- function(F, C, B, params, tol = 1e-10, niter = 200L) {
    .Call('FLife_stockCPP', PACKAGE = 'FLife', F, C, B, params, tol, niter)
}

fCPP <- function(F, C, B, params, tol = 1e-10, niter = 200L) {
    .Call('FLife_fCPP', PACKAGE = 'FLife', F, C, B, params, tol, niter)
}

rcpp_hello_world <- function() {
    .Call('FLife_rcpp_hello_world', PACKAGE = 'FLife')
}

